name: VyOS v1.3.x LTS Release

on:
  workflow_dispatch:

env:
  GIT_CLONE_URL: https://github.com/ashimov/vyos-build
  BRANCH: equuleus
  ARCHITECTURE: amd64
  BUILD_BY: berik@ashimov.com
  BUILD_TYPE: release
  VERSION: 1.3.7
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/
  VYOS_MIRROR: http://5.63.112.27/equuleus
  APT_KEY_URL: http://5.63.112.27/apt.gpg.key

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          curl -o ./apt.gpg.key $APT_KEY_URL
          sudo make clean || true
          sudo ./configure --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION-$(date +%Y%m%d%H%M) --vyos-mirror $VYOS_MIRROR --custom-apt-key ./apt.gpg.key
          sudo make iso

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso
          path: vyos-build/build/vyos-${{ env.VERSION }}-*.iso

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
        shell: bash

      - name: Create and push tag
        working-directory: ./vyos-build
        run: |
          git tag -a v${{ env.VERSION }} -m "VyOS v${{ env.VERSION }} LTS Release"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git v${{ env.VERSION }}
        shell: bash

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso
          path: vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          asset=$(find ./vyos-${{ env.VERSION }}-${{ env.ARCHITECTURE }}-iso/ -name "vyos-${{ env.VERSION }}-*.iso" | xargs)
          tag_name="v${{ env.VERSION }}"
          gh release create "$tag_name" --notes "VyOS v${{ env.VERSION }} LTS Release"
          gh release upload "$tag_name" "$asset"

  delete_old_workflow_runs:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 31
