name: VyOS v1.3.x LTS Release
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.3.*'

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/
  BRANCH: equuleus
  BUILD_ARCH: amd64
  BUILD_BY: berik@ashimov.com
  BUILD_TYPE: release
  BUILD_VERSION: 1.3.7
  VYOS_MIRROR: http://5.63.112.27/equuleus
  APT_KEY_URL: http://5.63.112.27/apt.gpg.key
  
  ARTIFACTS_DIR: artifacts
  WORKING_DIR: vyos-build
  STATUS_SUCCESS: "::set-output name=status::success"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Source Code
        run: |
          git clone -b $BRANCH --single-branch $GIT_CLONE_URL $WORKING_DIR
          cd $WORKING_DIR
          ./configure --architecture $BUILD_ARCH --build-by $BUILD_BY --build-type $BUILD_TYPE --version $BUILD_VERSION
          mkdir -p ./$ARTIFACTS_DIR

      - name: Download APT key
        run: |
          mkdir -p /vyos/apt-keys
          wget -O /vyos/apt-keys/apt.gpg.key $APT_KEY_URL

      - name: Build ISO Image
        id: iso
        working-directory: ./${{ env.WORKING_DIR }}
        run: |
          sudo make clean || true
          sudo ./build-vyos-image iso --architecture $BUILD_ARCH --build-by $BUILD_BY --build-type $BUILD_TYPE --version $BUILD_VERSION --vyos-mirror $VYOS_MIRROR --custom-apt-key /vyos/apt-keys/apt.gpg.key
          echo $STATUS_SUCCESS
          cp -f ./build/vyos-$BUILD_VERSION-$BUILD_ARCH.iso ./$ARTIFACTS_DIR/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vyos-${{ env.BUILD_VERSION }}-${{ env.BUILD_ARCH }}-images
          path: ${{ env.WORKING_DIR }}/${{ env.ARTIFACTS_DIR }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: vyos-${{ env.BUILD_VERSION }}-${{ env.BUILD_ARCH }}-images

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: VyOS v${{ env.BUILD_VERSION }} LTS Release
          body: VyOS v${{ env.BUILD_VERSION }} LTS Release
          draft: false
          prerelease: false
          files: |
            ${{ env.WORKING_DIR }}/${{ env.ARTIFACTS_DIR }}/vyos-${{ env.BUILD_VERSION }}-${{ env.BUILD_ARCH }}.iso
